### ISSUE TITLE
Problem in Arduino IDE

### ISSUE THREAD

**Issue by Lord-Felidae** [TinkerKit/TinkerKit#9]
This mostly involves this error message:

Arduino: 1.6.9 (Windows 10), Board: "Arduino Esplora"

In file included from C:\Users\eddie\Documents\Arduino\EsploraTest\EsploraTest.ino:1:0:

C:\Users\eddie\Documents\Arduino\libraries\TinkerKit-master/TinkerKit.h:222:33: error: 'constexpr' needed for in-class initialization of static data member 'const float TKThermistor::ADCres' of non-integral type [-fpermissive]

```
 const static float ADCres = 1023.0;

                             ^
```

C:\Users\eddie\Documents\Arduino\libraries\TinkerKit-master/TinkerKit.h:224:33: error: 'constexpr' needed for in-class initialization of static data member 'const float TKThermistor::Kelvin' of non-integral type [-fpermissive]

```
 const static float Kelvin = 273.15; // 0Â°C = 273.15 K

                             ^
```

C:\Users\eddie\Documents\Arduino\libraries\TinkerKit-master/TinkerKit.h:226:31: error: 'constexpr' needed for in-class initialization of static data member 'const float TKThermistor::Ginf' of non-integral type [-fpermissive]

```
 const static float Ginf = 120.6685; // Ginf = 1/Rinf

                           ^
```

In file included from C:\Users\eddie\Documents\Arduino\EsploraTest\EsploraTest.ino:1:0:

C:\Users\eddie\Documents\Arduino\libraries\TinkerKit-master/TinkerKit.h:293:32: error: 'constexpr' needed for in-class initialization of static data member 'const float TKAccelerometer::_gain' of non-integral type [-fpermissive]

```
 const static float _gain = 1.414;

                            ^
```

exit status 1

**Comment by Lord-Felidae** [comment]
@TinkerKit anyone can help me plz

**Comment by ptillemans** [comment]
Just in case it might help anyone who ends up on this page.

The compiler complains because the C++ standard disallows the use of constants which need to be allocated anyway as part of object initialization. So integral types are allowed, but floaty things not.

The solution for the code should be to use 'constexpr' rather than 'const' to tell the compiler to treat it differently.

For users just wanting to compile things, add the '-fpermissive' flag to the compiler build flags.

**Comment by ptillemans** [comment]
When pull request #6 is applied this flag would no longer be needed.
